import { SupplyData } from '../../types/supply';

export const cards: SupplyData[] = [
  {
    id: '154814',
    date: '2024-06-12',
    city: 'Тверь',
    quantity: 99922,
    supplyType: 'Короб',
    warehouseName: 'Внуково',
    warehouseAddress: 'пр. Победы, д. 25, Санкт-Петербург',
    status: 'В пути',
  },
  {
    id: '154222',
    date: '2024-06-12',
    city: 'Москва',
    quantity: 2333,
    supplyType: 'Монопаллета',
    warehouseName: 'Белая дача',
    warehouseAddress: 'пр. Ленинский, д. 7, Новосибирск',
    status: 'В пути',
  },
  {
    id: '154333',
    date: '2024-06-12',
    city: 'Москва',
    quantity: 2312,
    supplyType: 'Монопаллета',
    warehouseName: 'Белая дача',
    warehouseAddress: 'пр. Ленинский, д. 7, Новосибирск',
    status: 'Задерживается',
  },
  {
    id: '154444',
    date: '2024-06-12',
    city: 'Москва',
    quantity: 1052310,
    supplyType: 'Монопаллета',
    warehouseName: 'Белая дача',
    warehouseAddress: 'пр. Ленинский, д. 7, Новосибирск',
    status: 'В пути',
  },
  {
    id: '154555',
    date: '2024-06-12',
    city: 'Москва',
    quantity: 10210,
    supplyType: 'Монопаллета',
    warehouseName: 'Белая дача',
    warehouseAddress: 'пр. Ленинский, д. 7, Новосибирск',
    status: 'В пути',
  },
];
